version: "3"

services:
  document:
    image: node:latest
    container_name: document
    working_dir: /document
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./api:/document
    command: npm run start:document
    networks:
      default:
  mock:
    image: node:latest
    container_name: mock
    working_dir: /mock
    ports:
      - "3001:3000"
    volumes:
      - ./api:/mock
    command: npm run start:mock
    networks:
      default:
  api:
    image: node:latest
    container_name: api
    working_dir: /api
    volumes:
      - ./api:/api
    ports:
      - "5000:5000"
    command: npm run start:api
    networks:
      default:
networks:
  default:
